<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurgeAuditErrorQueryService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Connectivity\Connection\Infrastructure\Audit\Persistence\PurgeAuditErrorQuery' shared service.
     *
     * @return \Akeneo\Connectivity\Connection\Infrastructure\Audit\Persistence\PurgeAuditErrorQuery
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Infrastructure/Audit/Persistence/PurgeAuditErrorQuery.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->privates['Akeneo\\Connectivity\\Connection\\Infrastructure\\Audit\\Persistence\\PurgeAuditErrorQuery'])) {
            return $container->privates['Akeneo\\Connectivity\\Connection\\Infrastructure\\Audit\\Persistence\\PurgeAuditErrorQuery'];
        }

        return $container->privates['Akeneo\\Connectivity\\Connection\\Infrastructure\\Audit\\Persistence\\PurgeAuditErrorQuery'] = new \Akeneo\Connectivity\Connection\Infrastructure\Audit\Persistence\PurgeAuditErrorQuery($a);
    }
}
