<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurgeConnectionErrorsQueryService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Connectivity\Connection\Infrastructure\ErrorManagement\Persistence\PurgeConnectionErrorsQuery' shared service.
     *
     * @return \Akeneo\Connectivity\Connection\Infrastructure\ErrorManagement\Persistence\PurgeConnectionErrorsQuery
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/Persistence/PurgeConnectionErrorsQuery.php';

        return $container->privates['Akeneo\\Connectivity\\Connection\\Infrastructure\\ErrorManagement\\Persistence\\PurgeConnectionErrorsQuery'] = new \Akeneo\Connectivity\Connection\Infrastructure\ErrorManagement\Persistence\PurgeConnectionErrorsQuery(($container->services['akeneo_connectivity.client.connection_error'] ?? $container->load('getAkeneoConnectivity_Client_ConnectionErrorService')));
    }
}
